### PR TITLE
Helpful error messages

### PR DESCRIPTION
**Pull request by giorgiosironi**

### CODE REVIEW

**Comment by NuclearRedeye** [comment]
@lsh-0 merge or close?

**Comment by lsh-0** [comment]
I'll take a look

**Comment by lsh-0** [comment]
hey @gnott , could I get you to take a quick look at the changes please? `econ-tools` was still on python2 and I'm curious where it's being used. Is it a developer tool or is it integrated somewhere and has just been overlooked?

**Comment by gnott** [comment]
I use this on occassion for when video metadata failure happen, and I've been using Python 3 already. For who else uses it, possibly Production?

There's a bucket with S3 notifications which can automatically start silent correction workflows, and I'm not sure if this library is used.

I can test out the changes in this branch on `continuumtest` and make some modifications if that's alright with you, otherwise I can just leave comments. For example, `IngestArticleZip` workflow will not work, it must be `InitialArticleZip`, etc.

**Comment by lsh-0** [comment]
> I can test out the changes in this branch on continuumtest and make some modifications if that's alright with you, otherwise I can just leave comments. 

whatever you think is best, I'm unfamiliar with the project.

the python2-isms were regarding `print` vs `print()` and it's possible those lines were never executed during routine usage so they never failed.

**Comment by gnott** [comment]
The `get_queue()` duplicate name is also weird, something I want to test to be sure it was using the one we expect.

**Comment by gnott** [comment]
Tested and modified the new script, it works. You can take a look @lsh-0 if it is still suitable.

A couple things I noticed that are perhaps out-of-scope for this PR we could include in a new issue for improvements:

1. `econtools/econ_workflow.py` - It has a usage suggestion that also includes the older `IngestArticleZip` workflow name, except when I try it with no arguments, `ArgumentParser` gives out an entirely different (and more correct) usage message, e.g.

```
$ source venv/bin/activate
$ PYTHONPATH=. AWS_DEFAULT_REGION=us-east-1 python econtools/econ_workflow.py 
usage: econ_workflow.py [-h] queue_name workflow_name [workflow_data]
econ_workflow.py: error: the following arguments are required: queue_name, workflow_name
```

I don't know there the `[-h]` is coming from. This could be cleaned up

2. `get_queue()` is also duplicated in `econtools/econ_dashprop.py`, it could probably import from `econtools.aws` the same as the other one.

**Review by gnott — APPROVED** [review]

**Comment by lsh-0** [comment]
This code doesn't receive much attention, if you can make the changes *now* we won't have to think about them in the future.

> I don't know there the [-h] is coming from

it's an `ArgumentParser` built-in. So is the 'usage' message which is why I appended our own `usage` message to the end of the `description` string.

**Comment by lsh-0** [comment]
> get_queue() is also duplicated in econtools/econ_dashprop.py, 

fixed. also added a new check and a maintainers file.

**Pull request merged**
