### PR TITLE
upgrade to boto3 and python3.8

### PR DESCRIPTION
**Pull request by lsh-0**
Upgrades econ-tools to Python 3.8 and boto3.

### CODE REVIEW

**Comment by lsh-0** [comment]
@gnott , I had to change the tests a bit but I think their intent is still being captured.

I can see that `econ-tools` is available in `elife-bot` instances but is otherwise not a project dependency: https://github.com/elifesciences/elife-bot-formula/blob/master/salt/elife-bot/feeder.sls

Are you able to give these a manual test to make sure things are actually working?

**Comment by gnott** [comment]
I found at least one modification to get it to work manually for me, I will commit them directly to this branch if that's alright.

**Comment by lsh-0** [comment]
Please do

**Comment by gnott** [comment]
Changes in the most recent two commits, works for me now. Thanks @lsh-0 for the update.

**Review by gnott — APPROVED** [review]

**Comment by lsh-0** [comment]
Thanks for the changes :)

**Pull request merged**
