### PR TITLE
Since the bot is deployed with the new bot/lax work, let’s change the…

### PR DESCRIPTION
**Pull request by Jenniferstrej**
… default workflow to the new one “IngestArticleZip”

### CODE REVIEW

**Comment by giorgiosironi** [comment]
It is deployed with `consider_Lax_elife_2_0` in `end2end`, but not in `prod` at the moment. If we consider http://jira.elifesciences.org:8080/browse/ELPP-1613 somewhat finished, we can switch the settings in `prod` too (maybe on Monday to have a full week of monitoring?) and then merge this.

**Comment by Jenniferstrej** [comment]
Well, Isn't it deployed with the new code but with the settings 'not considering lax'? I saw it in master so I figured. But if not, that's fine, we deploy next week, thanks! 👍

**Comment by giorgiosironi** [comment]
I'm not sure if this depends only on the code or also on the configuration to be there, but I'd like to realign `end2end` and `prod` anyway so that we don't have to keep in mind where the settings are different from normal. I'll write on ELPP-1613.

**Comment by giorgiosironi** [comment]
Will merge this right after standup and having enabled the new ingests on production.

**Pull request merged**
